# Generated by Django 2.2.5 on 2022-03-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220307_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='langauge',
            field=models.CharField(choices=[('en', 'English'), ('kr', 'Korean')], max_length=20, null=True),
        ),
    ]
